#!/usr/bin/env bash
#
# Re-fetch the empirical sources behind the shock library's calibration.
#
#   docs/economic-shocks/fetch-sources.sh
#
# Everything here has a scripted route (unlike the tax corpora — see
# docs/au-tax/SOURCES.md). Series ids and what each one is FOR are in
# docs/economic-shocks/SOURCES.md; the numbers derived from them are in
# MEASUREMENTS.md, regenerated by scripts/probes/measure-shock-history.mjs.
#
set -euo pipefail
cd "$(dirname "$0")/data"

fred() {   # fred <series-id>
  echo "  FRED  $1"
  curl -sSL --fail --max-time 60 -o "FRED-$1.csv" \
    "https://fred.stlouisfed.org/graph/fredgraph.csv?id=$1"
}

echo "US / global equity + volatility"
fred SPASTT01USM661N     # OECD share prices, US, monthly index 1957-
fred SPASTT01AUM661N     # OECD share prices, Australia, same methodology 1958-
fred NASDAQCOM           # Nasdaq Composite, daily 1971-
fred VIXCLS              # CBOE VIX, daily 1990-
fred DIVIDEND            # BEA net corporate dividend payments, quarterly 1947-

echo "Prices"
fred CPIAUCSL            # US CPI-U, all items, SA, monthly 1947-
fred CPALTT01AUQ659N     # OECD CPI Australia, quarterly YoY %
fred CPIAUCNS            # US CPI-U, NSA (for full-history YoY)

echo "US policy + term structure"
fred FEDFUNDS            # effective fed funds, monthly 1954-
fred MPRIME              # bank prime loan rate, monthly 1949-
fred MORTGAGE30US        # Freddie Mac 30-yr fixed mortgage, weekly 1971-
for t in 1 2 5 10 30; do fred "DGS$t"; done   # Treasury constant maturity, daily
fred GS1; fred GS10                            # monthly equivalents, longer history
fred T10Y2Y              # 10y minus 2y spread, daily 1976-

echo "AU policy + term structure"
fred IR3TIB01AUM156N     # AU 3-month interbank, monthly 1968-
fred IRLTLT01AUM156N     # AU 10-year government bond yield, monthly 1969-
echo "  RBA   F1.1 cash rate target"
curl -sSL --fail --max-time 60 -o RBA-F1.1-money-market.csv \
  "https://www.rba.gov.au/statistics/tables/csv/f1.1-data.csv"

echo "FX"
fred DEXUSAL             # USD per AUD, daily 1971-
fred TWEXMMTH            # trade-weighted USD, major currencies, monthly 1973-2019
fred DTWEXM              # same, daily 1973-2019

echo "Real estate"
fred CSUSHPINSA          # Case-Shiller US national home price index, monthly 1987-
fred SFXRSA              # Case-Shiller San Francisco, monthly 1987-
fred QUSN628BIS          # BIS residential property prices, US, nominal, quarterly 1970-
fred QAUN628BIS          # BIS residential property prices, Australia, nominal
fred QAUR628BIS          # BIS residential property prices, Australia, real

echo "Cycle dating"
fred USREC               # NBER-based US recession indicator, monthly
echo "  NBER  business cycle reference dates"
curl -sSL --fail --max-time 60 -o /tmp/nber-cycles.html \
  "https://www.nber.org/research/data/us-business-cycle-expansions-and-contractions"
python3 ../nber-to-txt.py /tmp/nber-cycles.html NBER-business-cycle-dates.txt

echo "S&P 500 monthly, 1871- (Shiller)"
# shillerdata.com serves the workbook behind a CDN blob URL; it is the .xls that
# accompanies *Irrational Exuberance*, and it carries the S&P 500 DIVIDEND series
# that no free FRED series does. Stored as the derived CSV only; the conversion
# needs python3 + xlrd (`python3 -m pip install xlrd`).
curl -sSL --fail --max-time 120 -o /tmp/shiller-ie_data.xls \
  "https://img1.wsimg.com/blobby/go/e5e77e0b-59d1-44d9-ab25-4763ac982e53/downloads/ie_data.xls"
python3 ../shiller-to-csv.py /tmp/shiller-ie_data.xls Shiller-SP500-monthly.csv

echo "done."
