/*
 * Copyright (c) 2026 Terry Packer.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 */

/**
 * `src/index.js` is generated by `npm run build:index`. If the generator ever emits
 * the same identifier from two modules, the result is a duplicate `import` binding —
 * a hard SyntaxError at module load, in a file nobody edits by hand.
 *
 * The failure mode is why this test exists rather than a code comment. It does not
 * fail one test; it fails EVERY test file that imports the package (~30 of them), all
 * reporting a bare "test failed" with no assertion output, because the module never
 * loads far enough to run anything. Diagnosing that from the suite output is slow and
 * looks like a catastrophic regression in whatever was last worked on. It has happened
 * twice, both times from `ASSET_CLASS`, which `asset-class.js` declares and
 * `target-cube.js` re-exports — and both times it was mistaken for a real breakage.
 *
 * `getExports` now attributes a re-exported name to its declaring module, so the
 * generator cannot produce this. This test asserts the committed artifact is clean, so
 * a stale or hand-edited `index.js` is caught by one legible failure instead.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const INDEX = fileURLToPath(new URL('../../src/index.js', import.meta.url));

test('src/index.js imports every identifier exactly once', () => {
  const src = readFileSync(INDEX, 'utf8');
  const seen = new Map();
  const duplicates = [];

  for (const m of src.matchAll(/^import \{ ([^}]*) \} from '(.*?)';$/gm)) {
    const [, names, from] = m;
    for (const name of names.split(',').map(s => s.trim()).filter(Boolean)) {
      if (seen.has(name)) duplicates.push(`${name}: ${seen.get(name)} and ${from}`);
      else seen.set(name, from);
    }
  }

  assert.ok(seen.size > 500, `only ${seen.size} imports parsed — the regex has drifted from the generator's output`);
  assert.deepEqual(duplicates, [],
    'duplicate import bindings in the generated index.js — re-run `npm run build:index`. '
    + 'A name declared in one module and re-exported by another must be attributed to '
    + 'the declaring one; see getExports in scripts/dev/build-index.js.');
});
